# Generated by Django 4.2.4 on 2025-05-21 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('cpf_cnpj', models.CharField(max_length=14)),
                ('email', models.CharField(max_length=80)),
                ('telefone', models.CharField(max_length=15)),
                ('tipo', models.CharField(max_length=30)),
                ('bairro', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=10)),
                ('endereco', models.CharField(max_length=50)),
                ('status_cliente', models.CharField(max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
