# Generated by Django 4.2.4 on 2025-05-21 01:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_utilizada', models.PositiveIntegerField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produto.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('valor_servico', models.FloatField()),
                ('status_servico', models.CharField(choices=[('ativo', 'Ativo'), ('desativado', 'Desativado')], default='ativo', max_length=12)),
                ('descricao_servico', models.CharField(max_length=100)),
                ('data_modificacao_servico', models.DateTimeField(default=datetime.datetime.now)),
                ('historico_valor_servico', models.JSONField(blank=True, default=list)),
                ('historico_data_modificacao', models.JSONField(blank=True, default=list)),
                ('produtos', models.ManyToManyField(through='servicos.ProdutoServico', to='produto.produto')),
            ],
        ),
        migrations.AddField(
            model_name='produtoservico',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='servicos.servico'),
        ),
    ]
