# Generated by Django 4.2.4 on 2025-05-24 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='descricao_servico',
            field=models.TextField(blank=True, null=True),
        ),
    ]
