# Generated by Django 4.2.4 on 2025-03-17 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('cpf_cnpj', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='CPF deve ter 11 dígitos ou CNPJ 14 dígitos.', regex='^\\d{11}|\\d{14}$')])),
                ('email', models.CharField(max_length=80)),
                ('telefone', models.CharField(max_length=15)),
                ('tipo', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=50)),
                ('cep', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=40)),
                ('status_cliente', models.CharField(max_length=20)),
            ],
        ),
    ]
