# Generated by Django 4.2.4 on 2025-05-21 01:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('valor', models.FloatField()),
                ('data_modificacao_compra', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_min', models.IntegerField()),
                ('quantidade_max', models.IntegerField()),
                ('quantidade_atual', models.IntegerField()),
                ('valor_produto_venda', models.FloatField()),
                ('data_modificacao_produto', models.DateTimeField(default=datetime.datetime.now)),
                ('historico_valor_venda', models.JSONField(blank=True, default=list)),
                ('historico_data_modificacao', models.JSONField(blank=True, default=list)),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estoque', to='produto.produto')),
            ],
        ),
    ]
