version: "3.8"

services:
  mariadb:
    image: mariadb:10.6
    container_name: mariadb_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: retifica
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - rede_docker

  backend:
    build: ./Sprint-3/backend
    container_name: sprint3-backend
    ports:
      - "8000:8000"
    depends_on:
      - mariadb
    environment:
      DB_NAME: retifica
      DB_USER: root
      DB_PASSWORD: root
      DB_HOST: mariadb
      DB_PORT: 3306
    networks:
      - rede_docker

  frontend:
    build: ./Sprint-3/frontend
    container_name: sprint3-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - rede_docker

volumes:
  mariadb_data:

networks:
  rede_docker:
    driver: bridge
