version: '3.8'

services:
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tcc
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234 
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./Sprint-1/backend
    ports:
      - "8000:8000"
    volumes:
      - ./Sprint-1/backend:/backend
    depends_on:
      - db
    environment:
      - DOCKERIZED=1
      

  frontend:
    build: ./Sprint-1/frontend
    ports:
      - "3000:3000"
    volumes:
      - ./Sprint-1/frontend:/frontend
    depends_on:
      - backend

volumes:
  db_data: