# Generated by Django 4.2.4 on 2025-04-14 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='data_modificacao_produto',
            field=models.DateField(auto_now=True),
        ),
    ]
