# Generated by Django 4.2.4 on 2025-04-24 06:09

import datetime
from django.db import migrations, models
from django.utils.timezone import now


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_alter_estoque_data_modificacao_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='estoque',
            name='historico_data_modificacao',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='estoque',
            name='historico_valor_venda',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='data_modificacao_produto',
            field=models.DateTimeField(default=now),
        ),
    ]
