# Generated by Django 4.2.4 on 2025-04-24 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0004_estoque_historico_data_modificacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='data_modificacao_produto',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
