# Generated by Django 4.2.4 on 2025-04-24 22:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_alter_estoque_data_modificacao_produto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='data_modificacao_produto',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
