# Generated by Django 4.2.4 on 2025-05-24 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendaproduto',
            name='observacao',
        ),
        migrations.RemoveField(
            model_name='vendaservico',
            name='observacao',
        ),
        migrations.AlterField(
            model_name='vendaproduto',
            name='forma_pagamento',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vendaproduto',
            name='situacao_venda',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vendaproduto',
            name='status_pagamento',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vendaservico',
            name='detalhes_pagamento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendaservico',
            name='forma_pagamento',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vendaservico',
            name='situacao_venda',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vendaservico',
            name='status_pagamento',
            field=models.CharField(max_length=20),
        ),
    ]
