# Generated by Django 4.2.4 on 2025-05-29 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_remove_vendaproduto_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendaitem',
            name='descricao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
