# Generated by Django 4.2.4 on 2025-04-23 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_servico', models.CharField(max_length=50)),
                ('valor_servico', models.FloatField()),
                ('status_servico', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo')], default='ativo', max_length=8)),
                ('descricao_servico', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ServicoValores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_servico', models.FloatField()),
                ('data_modificacao_servico', models.DateField(auto_now_add=True)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico_valores', to='servicos.servico')),
            ],
        ),
    ]
