# Generated by Django 4.2.4 on 2025-05-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0006_alter_estoque_data_modificacao_produto'),
        ('servicos', '0002_rename_nome_servico_servico_nome_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='produtos',
            field=models.ManyToManyField(related_name='servicos_utilizados', to='produto.produto'),
        ),
    ]
