# Generated by Django 4.2.4 on 2025-05-13 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_servico_produtos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='status_servico',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('desativado', 'Desativado')], default='ativo', max_length=12),
        ),
    ]
