# Generated by Django 4.2.4 on 2025-06-11 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_alter_produto_descricao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='valor',
            new_name='valor_compra',
        ),
    ]
