# Generated by Django 4.2.4 on 2025-05-28 01:53

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_alter_produto_descricao'),
        ('servicos', '0002_alter_servico_descricao_servico'),
        ('clientes', '0001_initial'),
        ('vendas', '0002_remove_vendaproduto_observacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendaproduto',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='vendaproduto',
            name='quantidade',
        ),
        migrations.AlterField(
            model_name='vendaproduto',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='vendaproduto',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='vendaservico',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas_cliente_servico', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='vendaservico',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas_servico', to='servicos.servico'),
        ),
        migrations.CreateModel(
            name='VendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produto.produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='vendas.vendaproduto')),
            ],
        ),
    ]
