# Generated by Django 4.2.4 on 2025-06-03 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_remove_vendaservico_servico_vendaservicoitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendaservicoitem',
            old_name='valor_unitario',
            new_name='valor_servico',
        ),
    ]
