# Generated by Django 4.2.4 on 2025-06-21 15:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_rename_valor_unitario_vendaservicoitem_valor_servico'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendaitem',
            name='valor_total_itens',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='vendaservicoitem',
            name='valor_total_itens',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='vendaproduto',
            name='data_venda',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='vendaservico',
            name='data_venda',
            field=models.DateTimeField(),
        ),
    ]
